defaults: 
  local: ../../../package-defaults.yaml
name: service-backfill
version: '1.0.0'
synopsis: Backfill service tables
category: Network
author: Social Technologies LTD
maintainer: Social Technologies LTD <technology@social.network>
copyright: (c) 2018 Social Technologies LTD
license: AGPL-3
ghc-options:
- -funbox-strict-fields
- -threaded
- -with-rtsopts=-N
- -with-rtsopts=-T
- -rtsopts
dependencies:
- base
- attoparsec
- brig-types
- bytestring
- bytestring
- bytestring-conversion
- cassandra-util
- conduit
- extended
- galley-types
- imports
- lens
- mtl
- optparse-applicative
- text
- time
- tinylog
- types-common
- unliftio
- uuid
executables:
  service-backfill:
    main: Main.hs
    source-dirs: src
