defaults: 
  local: ../../../package-defaults.yaml
name: billing-team-member-backfill
version: '1.0.0'
synopsis: Backfill billing_team_member table
category: Network
author: Social Technologies LTD
maintainer: Social Technologies LTD <technology@social.network>
copyright: (c) 2020 Social Technologies LTD
license: AGPL-3
ghc-options:
- -funbox-strict-fields
- -threaded
- -with-rtsopts=-N
- -with-rtsopts=-T
- -rtsopts
dependencies:
- base
- cassandra-util
- containers
- galley-types
- imports
- optparse-applicative
- text
- lens
- tinylog
- uuid
- types-common
- unliftio
- conduit
executables:
  billing-team-member-backfill:
    main: Main.hs
    source-dirs: src
